apiVersion: v1
kind: ConfigMap
metadata:
  name: console-service-logcfg
  namespace: openfuyao-system
data:
  console-service.yaml: |
    Level: info
    EncoderType: console
    Path: /var/log/console-service
    FileName: root.log
    MaxSize: 20
    MaxBackups: 5
    MaxAge: 30
    LocalTime: false
    Compress: true
    OutMod: both

