apiVersion: v1
kind: Service
metadata:
  name: console-service
  namespace: openfuyao-system
  labels:
    app: console-service
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  type: ClusterIP
  ports:
    - name: transport
      port: 80
      protocol: TCP
      targetPort: 9037
  publishNotReadyAddresses: true
  selector:
    app: console-service
  sessionAffinity: None

